// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABddjiKfw7z6iGtUiVXANlHtmjGclY_M8',
    appId: '1:841702444972:web:44caee76066e3f29ce3409',
    messagingSenderId: '841702444972',
    projectId: 'chat-app-cc88e',
    authDomain: 'chat-app-cc88e.firebaseapp.com',
    storageBucket: 'chat-app-cc88e.firebasestorage.app',
    measurementId: 'G-HCWWXHFJB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKddY7mm5QFYjCmlrdDgmMlD28uIYJeC4',
    appId: '1:841702444972:android:70ee8d5eb3883fface3409',
    messagingSenderId: '841702444972',
    projectId: 'chat-app-cc88e',
    storageBucket: 'chat-app-cc88e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNqDTeXIrEtj8n4yhuRIEsZqUnSfCi7U',
    appId: '1:841702444972:ios:44cf36f81d3f9127ce3409',
    messagingSenderId: '841702444972',
    projectId: 'chat-app-cc88e',
    storageBucket: 'chat-app-cc88e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvNqDTeXIrEtj8n4yhuRIEsZqUnSfCi7U',
    appId: '1:841702444972:ios:44cf36f81d3f9127ce3409',
    messagingSenderId: '841702444972',
    projectId: 'chat-app-cc88e',
    storageBucket: 'chat-app-cc88e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABddjiKfw7z6iGtUiVXANlHtmjGclY_M8',
    appId: '1:841702444972:web:9ffac62144513787ce3409',
    messagingSenderId: '841702444972',
    projectId: 'chat-app-cc88e',
    authDomain: 'chat-app-cc88e.firebaseapp.com',
    storageBucket: 'chat-app-cc88e.firebasestorage.app',
    measurementId: 'G-CCCBRB5RME',
  );
}
